//
// Created by arthur on 03/10/17.
//

#ifndef GENETICALGORITHM_CONFIG_H
#define GENETICALGORITHM_CONFIG_H

#define NUMBER_OF_GENERATIONS 15
#define NUMBER_OF_CHROMOSONES 50
#define SIZE_OF_POPULATION 50

#define PROBABILITY_OF_CROSSOVER 100
#define PROBABILITY_OF_MUTATION 3

#endif //GENETICALGORITHM_CONFIG_H
