#ifndef GENETICALGORITHM_CONFIG_H
#define GENETICALGORITHM_CONFIG_H

#define NUMBER_OF_GENERATIONS 50
#define NUMBER_OF_CHROMOSONES 60
#define SIZE_OF_POPULATION 50

#define PROBABILITY_OF_CROSSOVER 100
#define PROBABILITY_OF_MUTATION 5

#define NUM_RULES 10

#define DATA_PATH "../data/data1.txt"
#define DATA_LENGTH 5
#define NUMBER_OF_DATA 64

#endif //GENETICALGORITHM_CONFIG_H
