#ifndef GENETICALGORITHM_CONFIG_H
#define GENETICALGORITHM_CONFIG_H

#define NUMBER_OF_GENERATIONS 100
#define NUMBER_OF_CHROMOSOMES 130
#define SIZE_OF_POPULATION 100

#define PROBABILITY_OF_CROSSOVER 100
#define PROBABILITY_OF_MUTATION 12

#define NUM_RULES 10
#define DATA_PATH "../data/data3.txt"
#define DATA_LENGTH 6
#define NUMBER_OF_DATA 2000

#endif //GENETICALGORITHM_CONFIG_H
