#ifndef GENETICALGORITHM_CONFIG_H
#define GENETICALGORITHM_CONFIG_H

#define NUMBER_OF_GENERATIONS 2000
#define NUMBER_OF_CHROMOSOMES 65
#define SIZE_OF_POPULATION 2000

#define PROBABILITY_OF_CROSSOVER 100
#define PROBABILITY_OF_MUTATION 20

#define DATA_STEP 0.1
#define NUM_RULES 5
#define DATA_PATH "../data/data3.txt"
#define DATA_LENGTH 6
#define NUMBER_OF_DATA 1600
#define NUMBER_OF_FOLDS 5
#define TOURNAMENT_SIZE 8

#endif //GENETICALGORITHM_CONFIG_H
