#ifndef GENETICALGORITHM_CONFIG_H
#define GENETICALGORITHM_CONFIG_H

#define NUMBER_OF_GENERATIONS 200
#define NUMBER_OF_CHROMOSOMES 70
#define SIZE_OF_POPULATION 200

#define PROBABILITY_OF_CROSSOVER 100
#define PROBABILITY_OF_MUTATION 12

#define NUM_RULES 6
#define DATA_PATH "../data/data2.txt"
#define DATA_LENGTH 6
#define NUMBER_OF_DATA 64

#endif //GENETICALGORITHM_CONFIG_H
